package com.taigu.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2018-01-18T16:48:29.227+08:00
 * Generated source version: 3.1.14
 * 
 */
@WebService(targetNamespace = "http://endpoint.taigu.com/", name = "IUploadDataAction")
@XmlSeeAlso({ObjectFactory.class})
public interface IUploadDataAction {

    @WebMethod(operationName = "UploadData_05")
    @RequestWrapper(localName = "UploadData_05", targetNamespace = "http://endpoint.taigu.com/", className = "com.taigu.endpoint.UploadData05")
    @ResponseWrapper(localName = "UploadData_05Response", targetNamespace = "http://endpoint.taigu.com/", className = "com.taigu.endpoint.UploadData05Response")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String uploadData05(
        @WebParam(name = "key", targetNamespace = "")
        java.lang.String key,
        @WebParam(name = "content", targetNamespace = "")
        java.lang.String content
    );

    @WebMethod(operationName = "UploadData_04")
    @RequestWrapper(localName = "UploadData_04", targetNamespace = "http://endpoint.taigu.com/", className = "com.taigu.endpoint.UploadData04")
    @ResponseWrapper(localName = "UploadData_04Response", targetNamespace = "http://endpoint.taigu.com/", className = "com.taigu.endpoint.UploadData04Response")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String uploadData04(
        @WebParam(name = "key", targetNamespace = "")
        java.lang.String key,
        @WebParam(name = "content", targetNamespace = "")
        java.lang.String content
    );

    @WebMethod(operationName = "UploadData")
    @RequestWrapper(localName = "UploadData", targetNamespace = "http://endpoint.taigu.com/", className = "com.taigu.endpoint.UploadData")
    @ResponseWrapper(localName = "UploadDataResponse", targetNamespace = "http://endpoint.taigu.com/", className = "com.taigu.endpoint.UploadDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String uploadData(
        @WebParam(name = "key", targetNamespace = "")
        java.lang.String key,
        @WebParam(name = "content", targetNamespace = "")
        java.lang.String content
    );

    @WebMethod(operationName = "UploadData_07")
    @RequestWrapper(localName = "UploadData_07", targetNamespace = "http://endpoint.taigu.com/", className = "com.taigu.endpoint.UploadData07")
    @ResponseWrapper(localName = "UploadData_07Response", targetNamespace = "http://endpoint.taigu.com/", className = "com.taigu.endpoint.UploadData07Response")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String uploadData07(
        @WebParam(name = "key", targetNamespace = "")
        java.lang.String key,
        @WebParam(name = "content", targetNamespace = "")
        java.lang.String content
    );

    @WebMethod(operationName = "UploadData_06")
    @RequestWrapper(localName = "UploadData_06", targetNamespace = "http://endpoint.taigu.com/", className = "com.taigu.endpoint.UploadData06")
    @ResponseWrapper(localName = "UploadData_06Response", targetNamespace = "http://endpoint.taigu.com/", className = "com.taigu.endpoint.UploadData06Response")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String uploadData06(
        @WebParam(name = "key", targetNamespace = "")
        java.lang.String key,
        @WebParam(name = "content", targetNamespace = "")
        java.lang.String content
    );

    @WebMethod(operationName = "UploadData_09")
    @RequestWrapper(localName = "UploadData_09", targetNamespace = "http://endpoint.taigu.com/", className = "com.taigu.endpoint.UploadData09")
    @ResponseWrapper(localName = "UploadData_09Response", targetNamespace = "http://endpoint.taigu.com/", className = "com.taigu.endpoint.UploadData09Response")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String uploadData09(
        @WebParam(name = "key", targetNamespace = "")
        java.lang.String key,
        @WebParam(name = "content", targetNamespace = "")
        java.lang.String content
    );

    @WebMethod(operationName = "UploadData_08")
    @RequestWrapper(localName = "UploadData_08", targetNamespace = "http://endpoint.taigu.com/", className = "com.taigu.endpoint.UploadData08")
    @ResponseWrapper(localName = "UploadData_08Response", targetNamespace = "http://endpoint.taigu.com/", className = "com.taigu.endpoint.UploadData08Response")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String uploadData08(
        @WebParam(name = "key", targetNamespace = "")
        java.lang.String key,
        @WebParam(name = "content", targetNamespace = "")
        java.lang.String content
    );

    @WebMethod(operationName = "UploadData_01")
    @RequestWrapper(localName = "UploadData_01", targetNamespace = "http://endpoint.taigu.com/", className = "com.taigu.endpoint.UploadData01")
    @ResponseWrapper(localName = "UploadData_01Response", targetNamespace = "http://endpoint.taigu.com/", className = "com.taigu.endpoint.UploadData01Response")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String uploadData01(
        @WebParam(name = "key", targetNamespace = "")
        java.lang.String key,
        @WebParam(name = "content", targetNamespace = "")
        java.lang.String content
    );

    @WebMethod(operationName = "UploadData_03")
    @RequestWrapper(localName = "UploadData_03", targetNamespace = "http://endpoint.taigu.com/", className = "com.taigu.endpoint.UploadData03")
    @ResponseWrapper(localName = "UploadData_03Response", targetNamespace = "http://endpoint.taigu.com/", className = "com.taigu.endpoint.UploadData03Response")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String uploadData03(
        @WebParam(name = "key", targetNamespace = "")
        java.lang.String key,
        @WebParam(name = "content", targetNamespace = "")
        java.lang.String content
    );

    @WebMethod(operationName = "UploadAllData")
    @RequestWrapper(localName = "UploadAllData", targetNamespace = "http://endpoint.taigu.com/", className = "com.taigu.endpoint.UploadAllData")
    @ResponseWrapper(localName = "UploadAllDataResponse", targetNamespace = "http://endpoint.taigu.com/", className = "com.taigu.endpoint.UploadAllDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String uploadAllData(
        @WebParam(name = "content", targetNamespace = "")
        java.lang.String content
    );

    @WebMethod(operationName = "UploadData_02")
    @RequestWrapper(localName = "UploadData_02", targetNamespace = "http://endpoint.taigu.com/", className = "com.taigu.endpoint.UploadData02")
    @ResponseWrapper(localName = "UploadData_02Response", targetNamespace = "http://endpoint.taigu.com/", className = "com.taigu.endpoint.UploadData02Response")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String uploadData02(
        @WebParam(name = "key", targetNamespace = "")
        java.lang.String key,
        @WebParam(name = "content", targetNamespace = "")
        java.lang.String content
    );
}
