package com.taigu.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2018-01-18T16:48:29.286+08:00
 * Generated source version: 3.1.14
 * 
 */
@WebServiceClient(name = "services", 
                  wsdlLocation = "http://ws.nxdsm.com:8070/services/UploadData?wsdl",
                  targetNamespace = "http://endpoint.taigu.com/") 
public class Services extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint.taigu.com/", "services");
    public final static QName UploadDataActionImplPort = new QName("http://endpoint.taigu.com/", "UploadDataActionImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://ws.nxdsm.com:8070/services/UploadData?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Services.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://ws.nxdsm.com:8070/services/UploadData?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Services(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Services(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Services() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Services(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Services(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Services(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IUploadDataAction
     */
    @WebEndpoint(name = "UploadDataActionImplPort")
    public IUploadDataAction getUploadDataActionImplPort() {
        return super.getPort(UploadDataActionImplPort, IUploadDataAction.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IUploadDataAction
     */
    @WebEndpoint(name = "UploadDataActionImplPort")
    public IUploadDataAction getUploadDataActionImplPort(WebServiceFeature... features) {
        return super.getPort(UploadDataActionImplPort, IUploadDataAction.class, features);
    }

}
